# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 73cb5072cdf62a23a2128b0e5e9c6002e91cf0988ff9abfa49cd5dd30c5145c9c1f50d5b1905606396563664c0dab21b3f90095220bade1a88173441a528c127

test:
  secret_key_base: f52635554d1dd04f7e960cf7330442735a068cefac79c5b9ccf2843b6efee03c0f6545de99cf9ecebc936ccf094060eb2a2fd7e767c4a875490bb37771242501

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
